// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjvcdtrofkzwrbugrbgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqdmNkdHJvZmt6d3JidWdyYmdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NTg0OTcsImV4cCI6MjA2MjMzNDQ5N30.ogjZVlb09fRGIhPPd4k9bOi16gowrIHbgiPNZAwuIK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);